image: node:latest

variables:
  AWS_REGION: us-east-1

stages:
  - test
  - deploy_function
  - test_deployed_function
  - deploy_pages

test:
  stage: test
  script:
    - npm install
    - npm test

production:
  stage: deploy_function
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - FAILURE_MESSAGE="Must define \$AWS_ACCESS_KEY_ID and \$AWS_SECRET_ACCESS_KEY. Add keys to $CI_PROJECT_URL/-/settings/ci_cd"
    - test -z "$AWS_SECRET_ACCESS_KEY" && echo $FAILURE_MESSAGE && exit 1
    - test -z "$AWS_ACCESS_KEY_ID" && echo $FAILURE_MESSAGE && exit 1
  script:
    - serverless deploy --stage production --verbose

  environment: production
