# service: gitlab-example
# provider:
#   name: aws
#   runtime: nodejs14.x

# functions:
#   hello:
#     handler: src/handler.hello
#     events:
#       - http: GET hello


service: gitlab-example
provider:
  name: aws
  region: ${env:AWS_REGION}
  runtime: nodejs14.x

functions:
  hello:
    handler: src/handler.lambdaHandler
    events:
      - http:
          path: hello
          method: get
          cors: true
